import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // A leading underscore marks a binding that must exist but is deliberately
      // not referenced — e.g. Next.js font loaders, which the framework requires
      // to be assigned to a module-scope const.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
  globalIgnores([
    // Defaults from eslint-config-next.
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',

    // Generated by gen_img.py, and regenerated by the build and CI. Linting
    // them would also fight Cloudflare's idiomatic `export default { fetch }`
    // Worker shape. CI verifies instead that they match the generator output.
    'index.js',
    'functions/pic.js',
  ]),
])

export default eslintConfig
